### ISSUE TITLE
Missing "jenn/core/schema.json"

### ISSUE THREAD

**Issue by alechouse97** [shb84/JENN#19]
Hello, I am coming from the [SMT python package](https://github.com/SMTorg/SMT) that looks to be using JENN under the hood.

When installing into a fresh environment, I had to manually pip install `jsonpointer` and `jsonschema` for JENN due to module not found errors. Furthermore, when running the code now, I am getting the error:

```
No such file or directory: '/local/mambaforge/envs/test/lib/python3.11/site-packages/jenn/core/schema.json'
```

Any advice on how to proceed? This seems to breaking SMT at the moment.

**Comment by shb84** [comment]
Thank you for bring this to light. It was indeed an oversight; dependencies were not properly enforced and json files had not been properly synced. The latest version (`jenn` v1.0.5) should address this. Are you still experiencing issues?
