### ISSUE TITLE
Problem with import in jenn (really recent)

### ISSUE THREAD

**Issue by Paul-Saves** [shb84/JENN#24]
The problem appears when importing   NeuralNet, it looks like  matplotlib.pyplot is not imported as plt in metrics

smt/surrogate_models/genn.py:12: in <module>
  from jenn.model import NeuralNet
    from . import core, model, synthetic, 
  from . import metrics,
 ax: Union[plt.Axes, None] = None,  # noqa: ANN401E   NameError: name 'plt' is not defined

**Comment by shb84** [comment]
Hi @Paul-Saves, sorry for the late reply. Are you still having this issue?

**Comment by Paul-Saves** [comment]
@shb84 Yes, many thanks!
